#! bash
pathprepend ~/anaconda3/bin
pathprepend ~/miniconda3/bin
#pathprepend /usr/local/Cellar/python/2.7.13_1/bin
pathprepend ~/Dropbox/Work/bins/tsv-utils/bin
pathprepend ~/git/data-science-at-the-command-line/tools
pathprepend /usr/local/opt/coreutils/libexec/gnubin
pathappend /usr/local/opt/go/libexec/bin
pathappend ~/.fzf/bin
pathappend ~/git/python-trezor/trezorlib
